<?php

use App\Modules\Items\Http\Controllers\ItemAnalysisController;
use App\Modules\Items\Http\Controllers\ItemBreakdownController;
use App\Modules\Items\Http\Controllers\ItemCatalogController;
use App\Modules\Items\Http\Controllers\ItemCompositionController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', 'active_user'])->group(function (): void {
    Route::get('/items/context', [ItemCatalogController::class, 'context']);
    Route::get('/items/maintenance-summary', [ItemCatalogController::class, 'maintenanceSummary']);
    Route::get('/items', [ItemCatalogController::class, 'index']);
    Route::get('/items/fndr/context', [ItemCatalogController::class, 'fndrContext']);
    Route::get('/items/fndr', [ItemCatalogController::class, 'fndrIndex']);
    Route::get('/items/fps/context', [ItemCatalogController::class, 'fpsContext']);
    Route::get('/items/fps', [ItemCatalogController::class, 'fpsIndex']);
    Route::get('/items/obras/context', [ItemCatalogController::class, 'obrasContext']);
    Route::get('/items/obras', [ItemCatalogController::class, 'obrasIndex']);
    Route::get('/items/proman/context', [ItemCatalogController::class, 'promanContext']);
    Route::get('/items/proman', [ItemCatalogController::class, 'promanIndex']);
    Route::get('/items/upre/context', [ItemCatalogController::class, 'upreContext']);
    Route::get('/items/upre', [ItemCatalogController::class, 'upreIndex']);
    Route::post('/items', [ItemCatalogController::class, 'store']);
    Route::get('/items/{item}/deactivate-impact', [ItemCatalogController::class, 'deactivateImpact']);
    Route::get('/items/{item}', [ItemCatalogController::class, 'show']);
    Route::put('/items/{item}', [ItemCatalogController::class, 'update']);
    Route::post('/items/{item}/files', [ItemCatalogController::class, 'updateFiles']);
    Route::post('/items/{item}/review', [ItemCatalogController::class, 'review']);
    Route::get('/items/{item}/composition/context', [ItemCompositionController::class, 'compositionContext']);
    Route::get('/items/{item}/composition', [ItemCompositionController::class, 'composition']);
    Route::get('/items/{item}/materials', [ItemCompositionController::class, 'materials']);
    Route::get('/items/{item}/materials/pdf', [ItemCompositionController::class, 'materialsPdf']);
    Route::get('/items/{item}/materials/xlsx', [ItemCompositionController::class, 'materialsXlsx']);
    Route::post('/items/{item}/materials/sync', [ItemCompositionController::class, 'syncMaterials']);
    Route::post('/items/{item}/materials', [ItemCompositionController::class, 'storeMaterial']);
    Route::get('/items/{item}/materials/total', [ItemCompositionController::class, 'materialsTotal']);
    Route::put('/items/{item}/materials/{itemInput}', [ItemCompositionController::class, 'updateMaterial']);
    Route::delete('/items/{item}/materials/{itemInput}', [ItemCompositionController::class, 'deleteMaterial']);
    Route::get('/items/{item}/labor', [ItemCompositionController::class, 'labor']);
    Route::get('/items/{item}/labor/pdf', [ItemCompositionController::class, 'laborPdf']);
    Route::get('/items/{item}/labor/xlsx', [ItemCompositionController::class, 'laborXlsx']);
    Route::post('/items/{item}/labor/sync', [ItemCompositionController::class, 'syncLabor']);
    Route::post('/items/{item}/labor', [ItemCompositionController::class, 'storeLabor']);
    Route::get('/items/{item}/labor/total', [ItemCompositionController::class, 'laborTotal']);
    Route::put('/items/{item}/labor/{itemInput}', [ItemCompositionController::class, 'updateLabor']);
    Route::delete('/items/{item}/labor/{itemInput}', [ItemCompositionController::class, 'deleteLabor']);
    Route::get('/items/{item}/machinery', [ItemCompositionController::class, 'machinery']);
    Route::get('/items/{item}/machinery/pdf', [ItemCompositionController::class, 'machineryPdf']);
    Route::get('/items/{item}/machinery/xlsx', [ItemCompositionController::class, 'machineryXlsx']);
    Route::post('/items/{item}/machinery/sync', [ItemCompositionController::class, 'syncMachinery']);
    Route::post('/items/{item}/machinery', [ItemCompositionController::class, 'storeMachinery']);
    Route::get('/items/{item}/machinery/total', [ItemCompositionController::class, 'machineryTotal']);
    Route::put('/items/{item}/machinery/{itemInput}', [ItemCompositionController::class, 'updateMachinery']);
    Route::delete('/items/{item}/machinery/{itemInput}', [ItemCompositionController::class, 'deleteMachinery']);
    Route::get('/items/{item}/total', [ItemCompositionController::class, 'globalTotal']);
    Route::get('/items/{item}/breakdowns/recalculate/pdf', [ItemBreakdownController::class, 'breakdownRecalculation']);
    Route::get('/items/{item}/breakdowns/recalculate/xlsx', [ItemBreakdownController::class, 'breakdownRecalculationXlsx']);
    Route::post('/items/{item}/breakdowns/recalculate', [ItemBreakdownController::class, 'breakdownRecalculation']);
    Route::get('/items/{item}/price-analysis', [ItemAnalysisController::class, 'priceAnalysis']);
    Route::get('/items/{item}/analisis-precios-unitarios', [ItemAnalysisController::class, 'legacyUnitPriceAnalysis']);
    Route::get('/items/{item}/analisis-precios-unitarios/pdf', [ItemAnalysisController::class, 'legacyUnitPriceAnalysisPdf']);
    Route::get('/items/{item}/analisis-precios-unitarios/xlsx', [ItemAnalysisController::class, 'legacyUnitPriceAnalysisXlsx']);
    Route::post('/items/{item}/price-recalculation', [ItemAnalysisController::class, 'priceRecalculation']);
    Route::get('/items/{item}/price-recalculation/pdf', [ItemAnalysisController::class, 'priceRecalculationPdf']);
    Route::get('/items/{item}/price-recalculation/xlsx', [ItemAnalysisController::class, 'priceRecalculationXlsx']);
});
