<?php

use App\Http\Controllers\Api\V1\ProjectReportSignatureController;
use App\Http\Controllers\Api\V1\SearchController;
use App\Http\Controllers\Api\V1\UserController;
use App\Modules\Projects\Http\Controllers\ProjectBudgetController;
use App\Modules\Projects\Http\Controllers\ProjectCatalogController;
use App\Modules\Projects\Http\Controllers\ProjectHistoryController;
use App\Modules\Projects\Http\Controllers\ProjectItemsController;
use App\Modules\Projects\Http\Controllers\ProjectReportController;
use App\Modules\Projects\Http\Controllers\ProjectTemplateController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', 'active_user'])->group(function (): void {
    Route::get('/projects/context', [ProjectCatalogController::class, 'context']);
    Route::get('/projects/create-context', [ProjectCatalogController::class, 'context']);
    Route::get('/projects', [ProjectCatalogController::class, 'index']);
    Route::get('/projects/map', [ProjectCatalogController::class, 'map']);
    Route::post('/projects', [ProjectCatalogController::class, 'store']);
    Route::get('/project-templates', [ProjectTemplateController::class, 'index']);
    Route::get('/project-templates/{template}', [ProjectTemplateController::class, 'show']);
    Route::put('/project-templates/{project}', [ProjectTemplateController::class, 'update']);
    Route::post('/project-templates/{template}/create-project', [ProjectTemplateController::class, 'createProject']);
    Route::post('/projects/{project}/template', [ProjectTemplateController::class, 'store']);
    Route::get('/projects/{project}/history', [ProjectHistoryController::class, 'history']);
    Route::get('/projects/{project}/versions', [ProjectCatalogController::class, 'versions']);
    Route::get('/projects/{project}/versions/compare', [ProjectCatalogController::class, 'compareVersions']);
    Route::post('/projects/{project}/versions', [ProjectCatalogController::class, 'createUpdatedVersion']);
    Route::post('/projects/{project}/finalize', [ProjectCatalogController::class, 'finalizeVersion']);
    Route::post('/projects/{project}/synchronize', [ProjectCatalogController::class, 'synchronizeVersion']);
    Route::post('/projects/{project}/input-snapshots/{snapshot}/exclude', [ProjectCatalogController::class, 'excludeVersionInput']);
    Route::get('/projects/{project}/report-warnings', [ProjectReportController::class, 'reportWarnings']);
    Route::get('/projects/{project}/signature-access', [ProjectReportSignatureController::class, 'projectAccess']);
    Route::put('/projects/{project}/signature-access', [ProjectReportSignatureController::class, 'updateProjectAccess']);
    Route::get('/projects/{project}/signature-status', [ProjectReportSignatureController::class, 'status']);
    Route::get('/projects/{project}', [ProjectCatalogController::class, 'show']);
    Route::put('/projects/{project}', [ProjectCatalogController::class, 'update']);
    Route::post('/projects/{project}/items/sync', [ProjectItemsController::class, 'syncItems']);
    Route::get('/projects/{project}/items', [ProjectItemsController::class, 'items']);
    Route::get('/projects/items/{item}/incidence-price', [ProjectItemsController::class, 'incidencePrice']);
    Route::post('/projects/{project}/budget-recalculation', [ProjectBudgetController::class, 'budgetRecalculation']);
    Route::get('/projects/{project}/budget-recalculation/pdf', [ProjectBudgetController::class, 'budgetRecalculationPdf']);
    Route::get('/projects/{project}/budget-recalculation/xlsx', [ProjectBudgetController::class, 'budgetRecalculationXlsx']);
    Route::get('/projects/{project}/budget-by-group', [ProjectBudgetController::class, 'budgetByGroup']);
    Route::get('/projects/{project}/budget-by-group/pdf', [ProjectReportController::class, 'budgetByGroupPdf']);
    Route::get('/projects/{project}/budget-by-group/xlsx', [ProjectReportController::class, 'budgetByGroupXlsx']);
    Route::get('/projects/{project}/incidence-summary', [ProjectBudgetController::class, 'incidenceSummary']);
    Route::get('/projects/{project}/incidence-summary/pdf', [ProjectReportController::class, 'incidenceSummaryPdf']);
    Route::get('/projects/{project}/incidence-summary/xlsx', [ProjectReportController::class, 'incidenceSummaryXlsx']);
    Route::get('/projects/{project}/general-budget/pdf', [ProjectReportController::class, 'generalBudgetPdf']);
    Route::get('/projects/{project}/general-budget/xlsx', [ProjectReportController::class, 'generalBudgetXlsx']);
    Route::get('/projects/{project}/input-breakdown/pdf', [ProjectReportController::class, 'inputBreakdownPdf']);
    Route::get('/projects/{project}/input-breakdown/xlsx', [ProjectReportController::class, 'inputBreakdownXlsx']);
    Route::get('/projects/{project}/inputs-report/pdf', [ProjectReportController::class, 'inputsReportPdf']);
    Route::get('/projects/{project}/inputs-report/xlsx', [ProjectReportController::class, 'inputsReportXlsx']);
    Route::get('/projects/{project}/grouped-inputs-report/pdf', [ProjectReportController::class, 'groupedInputsReportPdf']);
    Route::get('/projects/{project}/grouped-inputs-report/xlsx', [ProjectReportController::class, 'groupedInputsReportXlsx']);
    Route::post('/projects/{project}/breakdown-calculation', [ProjectBudgetController::class, 'breakdownCalculation']);
    Route::get('/projects/{project}/unit-prices', [ProjectBudgetController::class, 'unitPrices']);
    Route::get('/projects/{project}/unit-prices/pdf', [ProjectReportController::class, 'unitPricesPdf']);
    Route::get('/projects/{project}/specifications/pdf', [ProjectReportController::class, 'specificationsPdf']);
    Route::post('/projects/{project}/reports/{reportKey}/sign', [ProjectReportSignatureController::class, 'sign']);
    Route::get('/projects/{project}/reports/{reportKey}/signatures', [ProjectReportSignatureController::class, 'signatures']);
    Route::get('/projects/{project}/reports/{reportKey}/signed/latest', [ProjectReportSignatureController::class, 'latestSigned']);
    Route::get('/projects/{project}/reports/{reportKey}/physical-signatures', [ProjectReportSignatureController::class, 'physicalSignatures']);
    Route::post('/projects/{project}/reports/{reportKey}/physical-signatures', [ProjectReportSignatureController::class, 'markPhysicalSignature']);
    Route::put('/projects/{project}/reports/{reportKey}/physical-signatures/positions', [ProjectReportSignatureController::class, 'updatePhysicalSignaturePositions']);
    Route::get('/projects/{project}/reports/{reportKey}/physical-signatures/pdf', [ProjectReportSignatureController::class, 'physicalSignaturesPdf']);
    Route::post('/projects/{project}/reports/{reportKey}/signature-preview', [ProjectReportSignatureController::class, 'preparePreview']);
    Route::patch('/projects/{project}/reports/{reportKey}/signature-preview/positions', [ProjectReportSignatureController::class, 'updatePreviewPositions']);
    Route::get('/projects/{project}/reports/{reportKey}/signature-preview/pdf', [ProjectReportSignatureController::class, 'previewPdf']);
    Route::post('/projects/{project}/signatures/{signature}/cancel', [ProjectReportSignatureController::class, 'cancel']);
    Route::get('/search/items', [SearchController::class, 'items']);
    Route::get('/users/{user}/display-name', [UserController::class, 'displayName']);
});
